services:
  devs:
    build:
      context: .
    ports:
      - "8000:8000"  # LangGraph Studio
    command: sleep infinity
  # db_mongodb:
  #   image: mongo:7
  #   restart: always
  #   ports:
  #     - 27017:27017
  #   command: mongod --bind_ip 0.0.0.0      
